"""250609_1630-test migration

Revision ID: 18f3e234c826
Revises: 
Create Date: 2025-06-09 16:30:39.804545+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '18f3e234c826'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('families',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('name', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_index(op.f('ix_families_code'), 'families', ['code'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('summary_text', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('summary_voice', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('family_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('kakao_id', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('profile_img', sa.Text(), nullable=True),
    sa.Column('family_id', sa.UUID(), nullable=True),
    sa.Column('family_role', sa.String(), nullable=True),
    sa.Column('is_guardian', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_index(op.f('ix_users_kakao_id'), 'users', ['kakao_id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_table('anomaly_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conv_id', sa.UUID(), nullable=True),
    sa.Column('anomaly_report', sa.Text(), nullable=True),
    sa.Column('anomaly_turn', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_table('turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conv_id', sa.UUID(), nullable=True),
    sa.Column('turn', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turns')
    op.drop_table('anomaly_reports')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_users_kakao_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('photos')
    op.drop_index(op.f('ix_families_code'), table_name='families')
    op.drop_table('families')
    # ### end Alembic commands ###
