"""Add foreign key between photos and families

Revision ID: 7f342d9ba8b0
Revises: 0026fd92f2b0
Create Date: 2025-06-01 11:45:23.242106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f342d9ba8b0'
down_revision: Union[str, None] = '0026fd92f2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('anomalies_reports_family_id_fkey'), 'anomalies_reports', type_='foreignkey')
    op.drop_column('anomalies_reports', 'family_id')
    op.drop_constraint(op.f('mentions_conv_id_fkey'), 'mentions', type_='foreignkey')
    op.create_foreign_key(None, 'mentions', 'photos', ['conv_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mentions', type_='foreignkey')
    op.create_foreign_key(op.f('mentions_conv_id_fkey'), 'mentions', 'conversations', ['conv_id'], ['id'])
    op.add_column('anomalies_reports', sa.Column('family_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('anomalies_reports_family_id_fkey'), 'anomalies_reports', 'families', ['family_id'], ['id'])
    # ### end Alembic commands ###
