"""initial migration

Revision ID: fd2a25e045ac
Revises: be16d589fb53
Create Date: 2025-06-10 23:08:23.248151+09:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd2a25e045ac'
down_revision: Union[str, None] = 'be16d589fb53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary_text', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('summary_voice', sa.Text(), nullable=True))
    op.add_column('photos', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'photos', 'users', ['user_id'], ['id'])
    op.drop_column('photos', 'summary_voice')
    op.drop_column('photos', 'summary_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('summary_text', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('photos', sa.Column('summary_voice', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'user_id')
    op.drop_column('conversations', 'summary_voice')
    op.drop_column('conversations', 'summary_text')
    # ### end Alembic commands ###
