"""더미 컬럼 테스트

Revision ID: 64690e81760b
Revises: 0bc8222de47d
Create Date: 2025-06-04 03:36:21.358090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64690e81760b'
down_revision: Union[str, None] = '0bc8222de47d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentions', sa.Column('dummy', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mentions', 'dummy')
    # ### end Alembic commands ###
