"""구조 수정

Revision ID: 6526a9b22616
Revises: eaf16e6ef254
Create Date: 2025-06-09 06:57:59.285590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6526a9b22616'
down_revision: Union[str, None] = 'eaf16e6ef254'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conv_id', sa.UUID(), nullable=True),
    sa.Column('anomaly_report', sa.Text(), nullable=True),
    sa.Column('anomaly_turn', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.create_table('turns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('conv_id', sa.UUID(), nullable=True),
    sa.Column('turn', sa.JSON(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_general_ci'
    )
    op.drop_table('anomalies_reports')
    op.drop_table('mentions')
    op.alter_column('photos', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.add_column('users', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('users', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'name')
    op.alter_column('photos', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.create_table('mentions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conv_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('question_answer', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('recorded_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversations.id'], name=op.f('mentions_conv_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('mentions_pkey'))
    )
    op.create_table('anomalies_reports',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('conv_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('event_report', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('event_interval', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conv_id'], ['conversations.id'], name=op.f('anomalies_reports_conv_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('anomalies_reports_pkey'))
    )
    op.drop_table('turns')
    op.drop_table('anomaly_reports')
    # ### end Alembic commands ###
