"""update photo model columns with json conversion

Revision ID: c56b1eede275
Revises: 1032e851d1bd
Create Date: 2025-06-09 05:13:12.519339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c56b1eede275'
down_revision: Union[str, None] = '1032e851d1bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('code', sa.String(), nullable=True))
    op.add_column('families', sa.Column('name', sa.String(length=40), nullable=True))
    op.drop_index(op.f('ix_families_family_code'), table_name='families')
    op.create_index(op.f('ix_families_code'), 'families', ['code'], unique=False)
    op.drop_column('families', 'family_code')
    op.add_column('photos', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('photos', sa.Column('season', sa.String(), nullable=True))
    op.add_column('photos', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column(
        'photos',
        'summary_text',
        existing_type=sa.TEXT(),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using='summary_text::json'
    )
    op.alter_column(
        'photos',
        'summary_voice',
        existing_type=sa.TEXT(),
        type_=postgresql.JSON(astext_type=sa.Text()),
        existing_nullable=True,
        postgresql_using='summary_voice::json'
    )
    op.alter_column('photos', 'photo_name',
               new_column_name='name',
               existing_type=sa.Text(),
               nullable=True)
    op.alter_column('photos', 'photo_url',
               new_column_name='url',
               existing_type=sa.Text(),
               nullable=True)
    op.drop_column('photos', 'story_season')
    op.drop_column('photos', 'story_nudge')
    op.drop_column('photos', 'story_year')
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_guardian', sa.Boolean(), nullable=True))
    op.alter_column('users', 'birthday',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'birthday',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('users', 'is_guardian')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'email')
    op.drop_column('users', 'password')
    op.add_column('photos', sa.Column('story_year', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('photos', sa.Column('story_nudge', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('photos', sa.Column('story_season', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('photos', 'name',
               new_column_name='photo_name',
               existing_type=sa.Text(),
               nullable=True)
    op.alter_column('photos', 'url',
               new_column_name='photo_url',
               existing_type=sa.Text(),
               nullable=True)
    op.alter_column('photos', 'family_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('photos', 'summary_voice',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('photos', 'summary_text',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('photos', 'description')
    op.drop_column('photos', 'season')
    op.drop_column('photos', 'year')
    op.add_column('families', sa.Column('family_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_families_code'), table_name='families')
    op.create_index(op.f('ix_families_family_code'), 'families', ['family_code'], unique=False)
    op.drop_column('families', 'name')
    op.drop_column('families', 'code')
    # ### end Alembic commands ###
