"""Fix Mention conv_id's FK

Revision ID: cfcd8d98dba0
Revises: 64690e81760b
Create Date: 2025-06-04 07:03:00.526976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cfcd8d98dba0'
down_revision: Union[str, None] = '64690e81760b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('mentions_conv_id_fkey'), 'mentions', type_='foreignkey')
    op.create_foreign_key(None, 'mentions', 'conversations', ['conv_id'], ['id'])
    op.drop_column('mentions', 'dummy')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mentions', sa.Column('dummy', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mentions', type_='foreignkey')
    op.create_foreign_key(op.f('mentions_conv_id_fkey'), 'mentions', 'photos', ['conv_id'], ['id'])
    # ### end Alembic commands ###
