"""컬럼명

Revision ID: eaf16e6ef254
Revises: c56b1eede275
Create Date: 2025-06-09 05:24:02.176952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf16e6ef254'
down_revision: Union[str, None] = 'c56b1eede275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'family_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'family_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
