"""datetime 수정 with photo and family

Revision ID: 01efb32a6f33
Revises: 6ccdb52e5ad1
Create Date: 2025-06-01 12:14:24.993738

"""
from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01efb32a6f33'
down_revision: Union[str, None] = '6ccdb52e5ad1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'family_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photos', 'family_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
