"""initial schema

Revision ID: 36d4e6ea489a
Revises: 256b31f2ce0f
Create Date: 2025-06-08 06:38:31.533110

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36d4e6ea489a'
down_revision: Union[str, None] = '256b31f2ce0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('family_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('families', 'family_name')
    # ### end Alembic commands ###
