"""photo 테이블에서 summary_text/summary_voice 제거

Revision ID: 981b9ac2e9ba
Revises: 7c95b0c77385
Create Date: 2025-06-10 18:14:22.121289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '981b9ac2e9ba'
down_revision: Union[str, None] = '7c95b0c77385'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
