"""initial schema

Revision ID: b84733d9d93b
Revises: 65744a8bd27c
Create Date: 2025-06-09 11:12:13.801195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84733d9d93b'
down_revision: Union[str, None] = '65744a8bd27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('code', sa.String(), nullable=True))
    op.add_column('families', sa.Column('name', sa.String(length=40), nullable=True))
    op.drop_index(op.f('ix_families_family_code'), table_name='families')
    op.create_index(op.f('ix_families_code'), 'families', ['code'], unique=False)
    op.drop_column('families', 'family_code')
    op.drop_column('families', 'family_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('families', sa.Column('family_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('families', sa.Column('family_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_families_code'), table_name='families')
    op.create_index(op.f('ix_families_family_code'), 'families', ['family_code'], unique=False)
    op.drop_column('families', 'name')
    op.drop_column('families', 'code')
    # ### end Alembic commands ###
