"""photo 테이블에서 summary_text/summary_voice 제거

Revision ID: c8a4d142ee82
Revises: 981b9ac2e9ba
Create Date: 2025-06-10 18:17:56.531944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a4d142ee82'
down_revision: Union[str, None] = '981b9ac2e9ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
