"""initial schema

Revision ID: e1cc7380109e
Revises: 36d4e6ea489a
Create Date: 2025-06-08 06:48:47.062530

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1cc7380109e'
down_revision: Union[str, None] = '36d4e6ea489a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('family_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('family_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'family_name')
    op.drop_column('users', 'family_code')
    # ### end Alembic commands ###
